name: CI Template
on:
  pull_request:
  push:
    branches: [ main ]

# This is a reusable starter template for simple CI builds.
# Replace or extend jobs and steps as needed.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Resolve branch name
        shell: bash
        env:
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          GITHUB_REF: ${{ github.ref }}
        run: |
          if [ -n "${GITHUB_HEAD_REF}" ]; then
            BRANCH=${GITHUB_HEAD_REF}
          else
            BRANCH=${{ github.ref_name }}
          fi
          echo "Resolved branch: $BRANCH"
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV

      - name: Install
        run: npm ci

      - name: Test
        run: npm test
