name: Called Workflow
on:
  workflow_call:
    inputs:
      input1:
        description: 'An example input'
        required: true
        type: string

jobs:
  do-work:
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.make_message.outputs.message }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - id: make_message
        name: Create message
        run: |
          echo "Received input: '${{ inputs.input1 }}'"
          echo "::set-output name=message::Processed '${{ inputs.input1 }}'"