name: Caller Workflow
on: [push]
jobs:
  call-display-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Call Display Variable Workflow
        uses: ./.github/workflows/calledeworkflow.yml@mybranch

